53. Home
aldhisttd/2023_5sore_apotek_fe pull request #40
Opened 2023-12-28 02:32 UTC by GebyRezeki

![WhatsApp Image 2023-12-27 at 23 34 52_67d54c4a](https://github.com/aldhisttd/2023_5sore_apotek_fe/assets/130050241/b094655f-344e-476c-b2ce-b819acde4512)

2023-12-28 03:32 UTC, aldhi88 requested changes

2023-12-28 03:32 UTC, aldhi88 commented on script/home.js
> +                            <img src="assets/img/`+obat[i].gambar+`" class="card-img-top" alt="" style="object-fit:cover;height:170px"/>
@GebyRezeki url gambarnya salah

2023-12-28 03:32 UTC, aldhi88 commented on script/home.js
> +                            <img src="assets/img/`+obat[i].gambar+`" class="card-img-top" alt="" style="object-fit:cover;height:170px"/>
![image](https://github.com/aldhisttd/2023_5sore_apotek_fe/assets/16351933/2be51519-6a4d-4f00-b2f2-49b368f7d124)

2023-12-28 03:38 UTC, GebyRezeki commented on script/home.js
> +                            <img src="`+ host +`upload/`+ obat[i].gambar +`" class="card-img-top" alt="" style="object-fit:cover;height:170px"/>
@aldhi88 
![image](https://github.com/aldhisttd/2023_5sore_apotek_fe/assets/130050241/89f34a18-1a08-4877-8fbc-2c332146f52f)

2023-12-29 06:22 UTC, aldhi88 commented on script/home.js
> +                            <img src="`+ host +`upload/`+ obat[i].gambar +`" class="card-img-top" alt="" style="object-fit:cover;height:170px"/>
@GebyRezeki ini salah, ingat nama gambar itu sudah ada `upload/` nya

2023-12-29 16:48 UTC, GebyRezeki commented on script/home.js
> +                            <img src="`+ host + obat[i].gambar +`" class="card-img-top" alt="" style="object-fit:cover;height:170px"/>
@aldhi88

2023-12-30 00:47 UTC, aldhi88 approved these changes

2023-12-30 00:47 UTC, merged