19.data delete kategori
aldhisttd/2023_5sore_apotek_fe pull request #6
Opened 2023-12-05 11:01 UTC by Arini261203

2023-12-05 11:07 UTC, aldhi88 requested changes
@Arini261203 , perbaiki revisi nya ya, ditunggu

2023-12-05 11:07 UTC, aldhi88 commented on admin/script/kategori.js
> +    url: host + "raed_kategori.php",
@Arini261203 salah ini API nya

2023-12-05 11:07 UTC, aldhi88 commented on admin/script/kategori.js
> +            <button id="edit" class="btn btn-primary" value="` +
ini harus nya link yang mengarah ke form edit @Arini261203

2023-12-06 10:48 UTC, Arini261203 commented on admin/script/kategori.js
> +            `">Edit</a>
sudah benar pak @aldhi88 ?

2023-12-06 10:55 UTC, aldhi88 approved these changes

2023-12-06 10:56 UTC, merged